DROP TABLE IF EXISTS gmv, waste, users CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login VARCHAR,
    password VARCHAR,
    role VARCHAR,
    CONSTRAINT pk_user
            PRIMARY KEY (id),
        CONSTRAINT UQ_USER_LOGIN
            UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS gmv (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR,
    amount DECIMAL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_gmv
            PRIMARY KEY (id),
    CONSTRAINT fk_gmv_to_user
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS waste (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR,
    amount DECIMAL,
    gmv_id BIGINT NOT NULL,
    CONSTRAINT pk_waste
            PRIMARY KEY (id),
        CONSTRAINT fk_waste_to_gmv
                FOREIGN KEY(gmv_id) REFERENCES gmv(id) ON DELETE CASCADE
);